import { connect, disconnect } from 'mongoose';
import * as dotenv from 'dotenv';
import { Question, QuestionSchema } from '../src/questions/schemas/question.schema';
import * as mongoose from 'mongoose';

dotenv.config();

async function checkRate() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI is not defined.');
    return;
  }
  
  await connect(uri);
  
  try {
    const QuestionModel = mongoose.model<Question>('Question', QuestionSchema);
    
    // 1. Total questions generated by AI
    const totalAi = await QuestionModel.countDocuments({
      $or: [{ source: 'ai_generated' }, { created_by: 'ai-generator' }]
    }).exec();
    
    // 2. Questions generated in the last 24 hours
    const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const count24h = await QuestionModel.countDocuments({
      $or: [{ source: 'ai_generated' }, { created_by: 'ai-generator' }],
      created_at: { $gte: oneDayAgo }
    }).exec();
    
    // 3. Questions generated in the last 7 days
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const count7d = await QuestionModel.countDocuments({
      $or: [{ source: 'ai_generated' }, { created_by: 'ai-generator' }],
      created_at: { $gte: sevenDaysAgo }
    }).exec();
    
    console.log('AI-Generated Questions Statistics:');
    console.log(`- Cumulative Total generated: ${totalAi}`);
    console.log(`- Generated in the last 24 hours: ${count24h}`);
    console.log(`- Generated in the last 7 days: ${count7d}`);
    
    // 4. Group by day for the last 7 days
    const dailyStats = await QuestionModel.aggregate([
      {
        $match: {
          $or: [{ source: 'ai_generated' }, { created_by: 'ai-generator' }],
          created_at: { $gte: sevenDaysAgo }
        }
      },
      {
        $group: {
          _id: { $dateToString: { format: '%Y-%m-%d', date: '$created_at' } },
          count: { $sum: 1 }
        }
      },
      {
        $sort: { _id: -1 }
      }
    ]).exec();
    
    console.log('\nDaily generation rate (Last 7 days):');
    if (dailyStats.length > 0) {
      dailyStats.forEach((stat: any) => {
        console.log(`- Date: ${stat._id}: ${stat.count} questions`);
      });
    } else {
      console.log('- No questions generated in the last 7 days.');
    }
    
    // 5. Group by subject
    const subjectStats = await QuestionModel.aggregate([
      {
        $match: {
          $or: [{ source: 'ai_generated' }, { created_by: 'ai-generator' }]
        }
      },
      {
        $group: {
          _id: '$subject',
          count: { $sum: 1 }
        }
      },
      {
        $sort: { count: -1 }
      }
    ]).exec();
    
    console.log('\nQuestions per Subject:');
    subjectStats.forEach((stat: any) => {
      console.log(`- ${stat._id}: ${stat.count} questions`);
    });
    
  } catch (err: any) {
    console.error('Error:', err.message);
  }
  
  await disconnect();
}

checkRate();
