export const SYLLABUS: Record<string, string[]> = {
  english: [
    'Lexis and Structure',
    'Comprehension',
    'Summary Writing',
    'Oral English',
    'Grammar and Syntax',
    'Idioms and Phrasal Verbs',
  ],
  mathematics: [
    'Number Bases',
    'Fractions, Decimals, Approximations and Percentages',
    'Indices, Logarithms and Surds',
    'Sets',
    'Polynomials',
    'Variation',
    'Inequalities',
    'Progression',
    'Binary Operations',
    'Matrices and Determinants',
    'Geometry',
    'Mensuration',
    'Trigonometry',
    'Calculus',
    'Statistics',
    'Probability',
  ],
  physics: [
    'Measurements and Units',
    'Motion (Kinematics and Dynamics)',
    'Gravitational Field',
    'Equilibrium of Forces',
    'Work, Energy and Power',
    'Friction',
    'Elastic Properties of Solids',
    'Fluids at Rest and in Motion',
    'Temperature and its Measurement',
    'Thermal Properties of Matter',
    'Heat Transfer',
    'Waves',
    'Sound Waves',
    'Light Waves',
    'Static Electricity',
    'Current Electricity',
    'Magnetism and Electromagnetism',
    'Modern Physics',
  ],
  chemistry: [
    'Separation of Mixtures and Purification of Chemical Substances',
    'Chemical Combination',
    'Kinetic Theory of Matter and Gas Laws',
    'Atomic Structure and Bonding',
    'Nuclear Chemistry',
    'Air and Water',
    'Solubility',
    'Environmental Pollution',
    'Acids, Bases and Salts',
    'Oxidation and Reduction',
    'Electrolysis',
    'Energy Changes',
    'Rates of Chemical Reaction',
    'Chemical Equilibria',
    'Non-metals and their Compounds',
    'Metals and their Compounds',
    'Organic Chemistry',
  ],
  biology: [
    'Variety of Organisms',
    'Form and Functions',
    'Ecology',
    'Genetics',
    'Evolution',
    'Plant Physiology',
    'Animal Physiology',
    'Reproduction',
    'Microorganisms',
  ],
  geography: [
    'Physical Geography',
    'Human Geography',
    'Economic Geography',
    'Regional Geography of Nigeria',
    'Map Reading and Interpretation',
    'Environmental Interaction',
  ],
  economics: [
    'Basic Economic Concepts',
    'Theory of Consumer Behaviour',
    'Theory of Production',
    'Market Structures',
    'National Income',
    'Money and Inflation',
    'Public Finance',
    'International Trade',
    'Economic Development',
    'Population',
  ],
  government: [
    'Basic Concepts in Government',
    'Forms of Government',
    'Political Ideologies',
    'Constitution',
    'Federalism',
    'Electoral Process',
    'Public Administration',
    'Foreign Policy',
    'International Organizations',
  ],
  literature: [
    'Literary Appreciation',
    'African Poetry',
    'Non-African Poetry',
    'African Drama',
    'Non-African Drama',
    'African Prose',
    'Non-African Prose',
    'Figures of Speech',
  ],
  commerce: [
    'Trade and Trade Facilitation',
    'Business Organizations',
    'Money and Banking',
    'Communication and Transport',
    'Insurance',
    'Marketing',
    'Consumer Protection',
  ],
  accounting: [
    'Principles of Accounting',
    'Cash Book and Bank Reconciliation',
    'Final Accounts of Sole Traders',
    'Partnership Accounts',
    'Company Accounts',
    'Manufacturing Accounts',
    'Departmental and Branch Accounts',
    'Public Sector Accounting',
  ],
  agriculture: [
    'General Agriculture',
    'Agronomy',
    'Animal Production',
    'Agricultural Economics and Extension',
    'Agricultural Technology',
  ],
  civic_education: [
    'Values and Ethics',
    'Citizenship',
    'Human Rights',
    'Democracy and Governance',
    'Constitutionalism',
    'Civil Society',
  ],
  crk: [
    'Creation and the Fall',
    'The Patriarchs',
    'The Exodus',
    'The Judges and Kings',
    'The Prophets',
    'The Gospels',
    'The Early Church',
    'Epistles',
  ],
  irk: [
    'Quran',
    'Hadith',
    'Tawhid (Islamic Theology)',
    'Fiqh (Islamic Jurisprudence)',
    'Sirah (Life of the Prophet)',
    'Islamic History',
    'Islamic Ethics and Morality',
  ],
  history: [
    'Historiography',
    'Pre-colonial Nigeria',
    'Colonial Nigeria',
    'Post-colonial Nigeria',
    'African History',
    'World History',
  ],
  further_mathematics: [
    'Pure Mathematics',
    'Coordinate Geometry',
    'Calculus',
    'Vectors and Mechanics',
    'Statistics and Probability',
    'Logic',
    'Matrices and Linear Transformations',
  ],
};
